[package]
name = "dmd-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
native = ["dep:dmd-core-sys"]

[dependencies]
thiserror.workspace = true
dmd-core-sys = { workspace = true, optional = true }

[lints]
workspace = true
