[package]
name = "dmd-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
native = ["dep:dmd-core-sys", "dmd-core-sys/native"]

[dependencies]
thiserror.workspace = true
dmd-core-sys = { workspace = true, optional = true }

[dev-dependencies]
dmd-core-sys.workspace = true

[lints]
workspace = true
